artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/bebc30a2bba94feb926ede8dca51f736/artifacts
end_time: 1756152385711
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bebc30a2bba94feb926ede8dca51f736
run_name: Default
run_uuid: bebc30a2bba94feb926ede8dca51f736
source_name: ''
source_type: 4
source_version: ''
start_time: 1756152385674
status: 4
tags: []
user_id: mle-user
