artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/da38a54aeea042518a888dd495ed6886/artifacts
end_time: 1756140810918
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: da38a54aeea042518a888dd495ed6886
run_name: Default
run_uuid: da38a54aeea042518a888dd495ed6886
source_name: ''
source_type: 4
source_version: ''
start_time: 1756140810908
status: 3
tags: []
user_id: mle-user
