artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/41b2efa14fc34f3581fb1b75f873a7f3/artifacts
end_time: 1756140814345
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 41b2efa14fc34f3581fb1b75f873a7f3
run_name: Default
run_uuid: 41b2efa14fc34f3581fb1b75f873a7f3
source_name: ''
source_type: 4
source_version: ''
start_time: 1756140814327
status: 3
tags: []
user_id: mle-user
