artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/e7e57c3b30e34eee95a3dfbb0f4f7b29/artifacts
end_time: 1756152367431
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e7e57c3b30e34eee95a3dfbb0f4f7b29
run_name: Default
run_uuid: e7e57c3b30e34eee95a3dfbb0f4f7b29
source_name: ''
source_type: 4
source_version: ''
start_time: 1756152367411
status: 4
tags: []
user_id: mle-user
