artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/f3f58d750c5948798ab36806e13eb7c7/artifacts
end_time: 1756152391509
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f3f58d750c5948798ab36806e13eb7c7
run_name: Default
run_uuid: f3f58d750c5948798ab36806e13eb7c7
source_name: ''
source_type: 4
source_version: ''
start_time: 1756152391474
status: 4
tags: []
user_id: mle-user
