artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/mlflow_experiments_store/0/bee7b1a17eb24724a622e63c2a5a7281/artifacts
end_time: 1756151690761
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bee7b1a17eb24724a622e63c2a5a7281
run_name: Default
run_uuid: bee7b1a17eb24724a622e63c2a5a7281
source_name: ''
source_type: 4
source_version: ''
start_time: 1756151690719
status: 3
tags: []
user_id: mle-user
