artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/c84fd87e1724467cbffd584673adccde/artifacts
end_time: 1756140661497
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c84fd87e1724467cbffd584673adccde
run_name: Default
run_uuid: c84fd87e1724467cbffd584673adccde
source_name: ''
source_type: 4
source_version: ''
start_time: 1756140661455
status: 3
tags: []
user_id: mle-user
