artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/mlflow_experiments_store/0/738b61a36f294320a41de4ff4d31d2e6/artifacts
end_time: 1756151674121
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 738b61a36f294320a41de4ff4d31d2e6
run_name: Default
run_uuid: 738b61a36f294320a41de4ff4d31d2e6
source_name: ''
source_type: 4
source_version: ''
start_time: 1756151674112
status: 4
tags: []
user_id: mle-user
