artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/8605669e626c4b45844e0928fcaade20/artifacts
end_time: 1756152409587
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8605669e626c4b45844e0928fcaade20
run_name: Default
run_uuid: 8605669e626c4b45844e0928fcaade20
source_name: ''
source_type: 4
source_version: ''
start_time: 1756152409551
status: 3
tags: []
user_id: mle-user
