artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/3f82fd91c688442eaddb25b641f45871/artifacts
end_time: 1756140779942
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3f82fd91c688442eaddb25b641f45871
run_name: Default
run_uuid: 3f82fd91c688442eaddb25b641f45871
source_name: ''
source_type: 4
source_version: ''
start_time: 1756140779926
status: 4
tags: []
user_id: mle-user
