artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/15cf629d89954d8a80c25b1ebf22b30d/artifacts
end_time: 1756140816357
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 15cf629d89954d8a80c25b1ebf22b30d
run_name: Default
run_uuid: 15cf629d89954d8a80c25b1ebf22b30d
source_name: ''
source_type: 4
source_version: ''
start_time: 1756140816332
status: 3
tags: []
user_id: mle-user
